name: Node.js

on: push

jobs:
  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile

      - name: ESLint
        run: yarn lint

      - name: Prettier
        run: yarn format:check
